<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Helpers\" />
    <Folder Include="Validators\" />
    <Folder Include="Repositories\Implementations\" />
    <Folder Include="Repositories\Interfaces\" />
    <Folder Include="Repositories\Models\" />
    <Folder Include="Repositories\UOWs\" />
    <Folder Include="Services\Implementations\" />
    <Folder Include="Services\Interfaces\" />
    <Folder Include="Services\Models\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DMS.Shared\DMS.Shared.csproj" />
    <ProjectReference Include="..\DLMS.Tenants\DLMS.Tenants.csproj" />
  </ItemGroup>

</Project>
