<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Helpers\" />
    <Folder Include="Validators\" />
    <Folder Include="Repositories\Implementations\" />
    <Folder Include="Repositories\Interfaces\" />
    <Folder Include="Repositories\Models\" />
    <Folder Include="Repositories\UOWs\" />
    <Folder Include="Services\Implementations\" />
    <Folder Include="Services\Interfaces\" />
    <Folder Include="Services\Models\" />
  </ItemGroup>

</Project>
