// <auto-generated />
using System;
using DLMS.Tenants.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DLMS.Tenants.Migrations
{
    [DbContext(typeof(SharedContext))]
    [Migration("20260922202000_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tenant")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DLMS.Tenants.Repositories.Models.PermissionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("DmsId")
                        .HasColumnType("uuid")
                        .HasColumnName("dms_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_time");

                    b.Property<string>("Value")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("varchar")
                        .HasDefaultValue("test")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("permissions", "tenant");
                });

            modelBuilder.Entity("DLMS.Tenants.Repositories.Models.RoleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<Guid>("DmsId")
                        .HasColumnType("uuid")
                        .HasColumnName("dms_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("varchar")
                        .HasDefaultValue("Inactive")
                        .HasColumnName("status");

                    b.Property<long>("UtilityId")
                        .HasColumnType("bigint")
                        .HasColumnName("utility_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UtilityId");

                    b.ToTable("roles", "tenant");
                });

            modelBuilder.Entity("DLMS.Tenants.Repositories.Models.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("address");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<Guid>("DmsId")
                        .HasColumnType("uuid")
                        .HasColumnName("dms_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_time");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("middle_name");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<long?>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("varchar")
                        .HasDefaultValue("Inactive")
                        .HasColumnName("status");

                    b.Property<long?>("UtilityId")
                        .HasColumnType("bigint")
                        .HasColumnName("utility_id");

                    b.Property<bool>("isAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("RoleId");

                    b.HasIndex("UtilityId");

                    b.ToTable("users", "tenant");
                });

            modelBuilder.Entity("DLMS.Tenants.Repositories.Models.UtilityEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("acronym");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<Guid>("ApiKey")
                        .HasColumnType("uuid")
                        .HasColumnName("api_key");

                    b.Property<long?>("ContactPersonId")
                        .HasColumnType("bigint")
                        .HasColumnName("contact_person");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<Guid>("DmsId")
                        .HasColumnType("uuid")
                        .HasColumnName("dms_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_time");

                    b.Property<string>("LogoPath")
                        .HasColumnType("text")
                        .HasColumnName("logo_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("varchar")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<int>("TimeZone")
                        .HasColumnType("integer")
                        .HasColumnName("time_zone");

                    b.Property<string>("WebsiteAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("website_address");

                    b.HasKey("Id");

                    b.HasIndex("ContactPersonId");

                    b.ToTable("Utilities", "tenant");
                });

            modelBuilder.Entity("permission_entity_role_entity", b =>
                {
                    b.Property<long>("permission_id")
                        .HasColumnType("bigint")
                        .HasColumnName("permission_id");

                    b.Property<long>("role_id")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.HasKey("permission_id", "role_id");

                    b.HasIndex("role_id");

                    b.ToTable("permission_entity_role_entity", "tenant");
                });

            modelBuilder.Entity("DLMS.Tenants.Repositories.Models.RoleEntity", b =>
                {
                    b.HasOne("DLMS.Tenants.Repositories.Models.UserEntity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("DLMS.Tenants.Repositories.Models.UtilityEntity", "Utility")
                        .WithMany()
                        .HasForeignKey("UtilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Utility");
                });

            modelBuilder.Entity("DLMS.Tenants.Repositories.Models.UserEntity", b =>
                {
                    b.HasOne("DLMS.Tenants.Repositories.Models.UserEntity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("DLMS.Tenants.Repositories.Models.RoleEntity", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.HasOne("DLMS.Tenants.Repositories.Models.UtilityEntity", "Utility")
                        .WithMany()
                        .HasForeignKey("UtilityId");

                    b.Navigation("CreatedBy");

                    b.Navigation("Role");

                    b.Navigation("Utility");
                });

            modelBuilder.Entity("DLMS.Tenants.Repositories.Models.UtilityEntity", b =>
                {
                    b.HasOne("DLMS.Tenants.Repositories.Models.UserEntity", "ContactPerson")
                        .WithMany()
                        .HasForeignKey("ContactPersonId");

                    b.Navigation("ContactPerson");
                });

            modelBuilder.Entity("permission_entity_role_entity", b =>
                {
                    b.HasOne("DLMS.Tenants.Repositories.Models.PermissionEntity", null)
                        .WithMany()
                        .HasForeignKey("permission_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PermissionRole_Permission");

                    b.HasOne("DLMS.Tenants.Repositories.Models.RoleEntity", null)
                        .WithMany()
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PermissionRole_Role");
                });

            modelBuilder.Entity("DLMS.Tenants.Repositories.Models.RoleEntity", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
